### ISSUE TITLE
Licence question

### ISSUE THREAD

**Issue by kyril-s** [techwithmanuel/untitledui-js#14]
Hi, can I use this npm in a SaaS platform that we are building and selling?

**Comment by creatorslook** [comment]
This is an open source library and you're free to use it in any application
you're building but restricted from but not limited to redistribution and
others stated in the license

**Comment by kyril-s** [comment]
Thanks!

**Comment by zukilover** [comment]
@techwithmanuel Sorry to reopen. I want to confirm, does this library comply with untitledui icon's [license here](https://www.untitledui.com/legal/license)?

It says we are not allowed to distribute, or otherwise grant rights to the files or assets within the files (in original or modified form) even for the free versions.

**Comment by techwithmanuel** [comment]
Hello @zukilover I understand your concerns, I'll get in touch with the untitled UI team for clarification and get back to you on this, but as for now do not redistribute this library or any part of it, thank you for pointing this out
